apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: nonrootpods
spec:
  crd:
    spec:
      names:
        kind: NonRootPods
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            label:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package com.microsoft.c12.podsnonroot

        violation[{"msg": msg, "details": {}}] {
        	not input.review.object.spec.securityContext.runAsNonRoot = true
        	msg := sprintf("pod %s is running as root", [input.review.name])
        }

        violation[{"msg": msg, "details": {}}] {
        	input.review.object.spec.securityContext.runAsUser == 0
        	msg := sprintf("pod %s has a UID of 0", [input.review.name])
        }
